#! /usr/bin/bash

adithya=200
devika=500
if [ $adithya -le $devika ]
 then
  echo "condition is true"
elif [ $adithya -ge $devika ]
 then
  echo "condition is false"
else
echo "condition is equal"
fi
